// Central Offer, Pricing, and Product Catalog for MYTHRA
// Editable via config/admin layer. Defaults to USD.

export interface OfferTier {
  id: string;
  code: string;
  name: string;
  persona: 'YOU' | 'FILMMAKER' | 'STUDIOS' | 'CAST';
  price: number;
  priceDisplay: string;
  standardPriceDisplay?: string;
  availability?: string;
  buyerPersona?: string;
  isStartingPrice?: boolean;
  isRecommended?: boolean;
  tagline: string;
  description: string;
  features: string[];
  deliverables: string[];
  turnaround?: string;
  revisions?: string;
  voiceCloningIncluded?: boolean;
  commercialUsageIncluded?: boolean;
  checkoutType: 'instant' | 'deposit' | 'application' | 'consultation' | 'free';
  ctaText: string;
  ctaHref: string;
}

export interface AddOn {
  id: string;
  name: string;
  price: number | 'custom';
  priceDisplay: string;
  description: string;
  applicableTiers: string[];
}

export interface OffersConfig {
  you: OfferTier[];
  cast: OfferTier[];
  youAddOns: AddOn[];
  filmmaker: OfferTier[];
  studios: OfferTier[];
}

export const mythraOffers: OffersConfig = {
  // ── MYTHRA YOU: Make My Own Film (Personalized Cinema) ──
  you: [
    {
      id: 'you-moment',
      code: 'MYTHRA_MOMENT',
      name: 'MYTHRA MOMENT',
      persona: 'YOU',
      price: 79,
      priceDisplay: '$79',
      tagline: 'A cinematic snapshot',
      description: 'Template-led cinematic scene starring one authorized person. Perfect for gifts, memorable social moments, and personal milestones.',
      features: [
        'Cinematic scene starring one authorized person',
        'Face likeness from approved high-res photos',
        'Name & title personalization',
        'Cinematic score & original sound design',
        '1080p master delivery (16:9 or 9:16)',
        'Private encrypted asset handling',
      ],
      deliverables: ['1080p Master Video (16:9 or 9:16)'],
      turnaround: '3–5 business days',
      checkoutType: 'instant',
      ctaText: 'Create Moment · $79',
      ctaHref: '/un1/you/start?tier=you-moment',
    },
    {
      id: 'you-trailer',
      code: 'MYTHRA_TRAILER',
      name: 'MYTHRA TRAILER',
      persona: 'YOU',
      price: 299,
      priceDisplay: '$299',
      isRecommended: true,
      tagline: 'Your life as a blockbuster film',
      description: 'Bespoke movie trailer with 5–8 cinematic story beats, custom screenplay premise, authorized face, and verified voice option.',
      features: [
        'Personalized movie trailer with custom premise',
        'One authorized lead character',
        'Authorized face & verified voice option',
        '5 to 8 cinematic story beats & custom world',
        'Custom narration, bespoke score & full sound mix',
        'Landscape master + vertical social cut',
      ],
      deliverables: ['1080p 16:9 Master', '1080p 9:16 Vertical Cut', 'Digital Film Poster Stills'],
      turnaround: '7–10 business days',
      checkoutType: 'instant',
      ctaText: 'Create My Trailer · $299',
      ctaHref: '/un1/you/start?tier=you-trailer',
    },
    {
      id: 'you-story',
      code: 'MYTHRA_STORY',
      name: 'MYTHRA STORY',
      persona: 'YOU',
      price: 1500,
      priceDisplay: 'From $1,500',
      isStartingPrice: true,
      tagline: 'A bespoke cinematic short film',
      description: 'Custom screenplay, storyboard, and original world design for 1–2 authorized characters with dedicated creative consultation.',
      features: [
        'Custom narrative short film experience',
        'Story interview or detailed creative questionnaire',
        'Original screenplay and storyboard approval',
        '1 or 2 authorized characters',
        'Authorized face & verified voice integration',
        'Bespoke world, score, edit & title design',
      ],
      deliverables: ['4K/1080p Master Cut', 'Vertical Teaser', 'Screenplay PDF', 'Key Art Gallery'],
      turnaround: '2–4 weeks',
      checkoutType: 'deposit',
      ctaText: 'Start Story Brief · From $1,500',
      ctaHref: '/un1/you/start?tier=you-story',
    },
    {
      id: 'you-legacy',
      code: 'MYTHRA_LEGACY',
      name: 'MYTHRA LEGACY',
      persona: 'YOU',
      price: 5000,
      priceDisplay: 'From $5,000',
      isStartingPrice: true,
      tagline: 'An enduring cinematic heirloom',
      description: 'Premium life story, founder documentary, wedding film, or family tribute with dedicated creative director and deep research.',
      features: [
        'Cinematic documentary or heirloom narrative film',
        'Dedicated Creative Director research call',
        'Full screenplay, character/world bible & production plan',
        'Multiple authorized characters where feasible',
        'Archival photo/video restoration integration',
        'Orchestral score & cinema-grade sound mix',
      ],
      deliverables: ['4K Cinema Master (ProRes/H.264)', 'Trailer Cut', 'Archival Hard Copy Box', 'Production Bible'],
      turnaround: '4–8 weeks',
      checkoutType: 'application',
      ctaText: 'Inquire for Legacy · From $5,000',
      ctaHref: '/un1/you/start?tier=you-legacy',
    },
  ],

  // ── MYTHRA CAST: Enter an Official MYTHRA Story ──
  cast: [
    {
      id: 'cast-fan-cameo',
      code: 'CAST_CAMEO',
      name: 'FAN CAMEO',
      persona: 'CAST',
      price: 500,
      priceDisplay: '$500',
      standardPriceDisplay: '$750–$1,000',
      availability: '3–5 per episode',
      buyerPersona: 'Superfan Collector — Wants proof that they permanently exist inside the story world.',
      tagline: 'Permanently exist inside the story world',
      description: 'Non-speaking ambient or background role inside an official upcoming MYTHRA Original. Your verified face integrated into canon cinema.',
      features: [
        '5–15 second appearance in an upcoming official episode',
        'Buyer’s authorized face integrated into the world',
        'Non-speaking background or ambient atmospheric role',
        'Official name placement in closing credits',
        'Custom digital character poster',
        'Social reveal asset for your channels',
      ],
      deliverables: ['Episode Appearance', 'Official Credit', 'Character Poster', 'Social Reveal Cut'],
      turnaround: 'Aligned with episode production schedule',
      checkoutType: 'application',
      ctaText: 'Apply for Fan Cameo · $500',
      ctaHref: '/un1/cast?tier=fan-cameo',
    },
    {
      id: 'cast-speaking-character',
      code: 'CAST_SPEAKING',
      name: 'SPEAKING CHARACTER',
      persona: 'CAST',
      price: 2500,
      priceDisplay: '$2,500',
      standardPriceDisplay: '$3,500–$5,000',
      availability: '1–3 per episode',
      isRecommended: true,
      buyerPersona: 'Recognition-Seeking Fan — Creator, aspiring actor, entrepreneur, or personality who wants credited screen presence.',
      tagline: 'Spoken dialogue and named presence in canon',
      description: 'Named role with dialogue lines inside an official MYTHRA Original. Includes character interview and credited performance.',
      features: [
        '15–45 seconds of meaningful presence in an upcoming episode',
        'Authorized face with optional verified voice',
        'One to three scripted dialogue lines',
        'Canon character name and defined story role',
        '30-minute character input interview with directors',
        'Official credited role in main end titles',
        'Character poster and vertical reveal asset',
      ],
      deliverables: ['Speaking Canon Role', 'Main Title Credit', 'Character Poster', 'Vertical Reveal Teaser'],
      turnaround: 'Aligned with episode production schedule',
      checkoutType: 'application',
      ctaText: 'Apply for Speaking Role · $2,500',
      ctaHref: '/un1/cast?tier=speaking-character',
    },
    {
      id: 'cast-featured-character',
      code: 'CAST_FEATURED',
      name: 'FEATURED CHARACTER',
      persona: 'CAST',
      price: 7500,
      priceDisplay: '$7,500',
      standardPriceDisplay: '$8,500–$12,500',
      availability: 'Maximum 1 per episode',
      buyerPersona: 'Public Identity Builder — Creator, founder or affluent fan who wants cultural identity, not another advertisement.',
      tagline: 'Multi-scene presence and custom story integration',
      description: 'Prominent custom character appearing across multiple scenes. Character traits inspired by your personality, with featured billing and premiere invite.',
      features: [
        'Approximately 1–3 minutes of screen time across multiple scenes',
        'Custom character design tailored to your traits',
        'Face, personality nuances & optional verified voice',
        '1-hour story interview with the narrative leads',
        'Featured character billing in credits',
        'Official trailer & poster reveal campaign',
        'Private online premiere access with creators',
        'Dedicated social campaign assets',
      ],
      deliverables: ['Multi-Scene Featured Role', 'Featured Credit', 'Trailer Reveal', 'Private Premiere Invite'],
      turnaround: 'Aligned with episode production schedule',
      checkoutType: 'application',
      ctaText: 'Apply for Featured Role · $7,500',
      ctaHref: '/un1/cast?tier=featured-character',
    },
    {
      id: 'cast-guest-hero',
      code: 'CAST_GUEST_HERO',
      name: 'EPISODE GUEST HERO',
      persona: 'CAST',
      price: 15000,
      priceDisplay: '$15,000 founding',
      standardPriceDisplay: '$20,000–$30,000+',
      availability: 'One selected applicant',
      buyerPersona: 'The Immortality Buyer — “I do not only want to watch culture. I want to become part of it.”',
      tagline: 'The central character of an official episode',
      description: 'Your life, values, or life experience inspires the central hero of a suitable MYTHRA Original. Full story workshop, multi-scene arc, and guest-star billing.',
      features: [
        'Central character arc across an entire official episode',
        'Your values, personality or selected experiences inspire the character',
        'Authorized face & optional verified voice performance',
        'Dedicated story workshop with lead showrunners',
        'Multiple-scene dramatic integration across the episode',
        'Special Guest Star billing in opening/closing titles',
        'Character poster & dedicated trailer reveal',
        'Private director conversation & private online premiere',
      ],
      deliverables: ['Lead Episode Arc', 'Guest Star Credit', 'Dedicated Trailer & Poster', 'Showrunner Workshop'],
      turnaround: 'Selective application & scheduling',
      checkoutType: 'application',
      ctaText: 'APPLY TO BECOME THE NEXT GUEST HERO',
      ctaHref: '/un1/cast?tier=guest-hero',
    },
  ],

  youAddOns: [
    {
      id: 'addon-extra-star',
      name: 'Additional Authorized Star',
      price: 149,
      priceDisplay: '+$79 (Moment) / +$149 (Trailer)',
      description: 'Include an additional consenting co-star with verified likeness authorization.',
      applicableTiers: ['you-moment', 'you-trailer', 'you-story', 'you-legacy'],
    },
    {
      id: 'addon-extra-language',
      name: 'Additional Language / Dub',
      price: 49,
      priceDisplay: '+$49 / language',
      description: 'Fully translated voice narration or dub with matched performance.',
      applicableTiers: ['you-trailer', 'you-story', 'you-legacy'],
    },
    {
      id: 'addon-priority-delivery',
      name: 'Priority Production Delivery',
      price: 'custom',
      priceDisplay: 'Quoted on capacity',
      description: 'Fast-tracked queue position subject to director schedule availability.',
      applicableTiers: ['you-moment', 'you-trailer'],
    },
    {
      id: 'addon-commercial-license',
      name: 'Commercial & Advertising License',
      price: 'custom',
      priceDisplay: 'Custom License',
      description: 'Permits commercial broadcast, paid ads, or corporate promotion (scoped separately from personal use).',
      applicableTiers: ['you-moment', 'you-trailer', 'you-story', 'you-legacy'],
    },
  ],

  // ── MYTHRA FILMMAKER: Production Education & Cohorts ──
  filmmaker: [
    {
      id: 'film-blueprint',
      code: 'MYTHRA_BLUEPRINT',
      name: 'THE ONE-PERSON STUDIO BLUEPRINT',
      persona: 'FILMMAKER',
      price: 0,
      priceDisplay: 'Free Access',
      tagline: 'The complete high-level system',
      description: 'An intensive workshop breakdown covering the complete 12-step Drama Method and story production pipeline.',
      features: [
        'Full production walkthrough and system architecture',
        'The 12-Step Drama Method architecture',
        'Tool-agnostic production pipeline diagram',
        'Character consistency & story engine framework',
        'Budget and feasibility benchmarks from the Genesis experiment',
      ],
      deliverables: ['Video Workshop Access', 'Studio Blueprint PDF Checklist'],
      turnaround: 'Instant Access',
      checkoutType: 'free',
      ctaText: 'Access Free Blueprint',
      ctaHref: '/un1/filmmaker/start?tier=film-blueprint',
    },
    {
      id: 'film-starter',
      code: 'MYTHRA_STARTER',
      name: 'MYTHRA STARTER',
      persona: 'FILMMAKER',
      price: 149,
      priceDisplay: '$149',
      tagline: 'Self-paced fundamentals',
      description: 'Comprehensive video training, prompt architectures, story bibles, and workflow templates to build your first narrative short film.',
      features: [
        'Self-paced 8-module comprehensive curriculum',
        'Story, character, storyboard, image, motion & sound modules',
        'Production templates, shot lists & character bible sheets',
        '1-year full platform access & future course updates',
        'Independent pacing with zero fluff or tool lock-in',
      ],
      deliverables: ['8 Modular Course Tracks', 'Production System Templates', 'Prompt & Workflow Library'],
      turnaround: 'Instant Access',
      checkoutType: 'instant',
      ctaText: 'Enroll in Starter · $149',
      ctaHref: '/un1/filmmaker/start?tier=film-starter',
    },
    {
      id: 'film-cohort',
      code: 'MYTHRA_COHORT',
      name: 'MYTHRA FILMMAKER COHORT',
      persona: 'FILMMAKER',
      price: 749,
      priceDisplay: '$749 Founding ($997 Standard)',
      isRecommended: true,
      tagline: '6-Week Live Production Accelerator',
      description: 'Weekly live production sessions, hands-on director feedback, and a structured sprint where you complete and publish your own portfolio film or trailer.',
      features: [
        '6-week intensive live cohort with weekly production sessions',
        'Direct feedback on screenplay, character bibles & rough cuts',
        'Character & world consistency across multi-scene edits',
        'Sound design, custom scoring & voice synthesis guidance',
        'Complete and publish 1 finished portfolio film or trailer',
        'Cohort community workspace during program + 90 days access',
        'Compute costs clearly disclosed upfront (~$50–$100 estimated)',
      ],
      deliverables: ['Live Weekly Sessions & Recordings', 'Director Project Reviews', 'Published Portfolio Film', 'Alumni Network Access'],
      turnaround: '6 Weeks (Next cohort starting soon)',
      checkoutType: 'instant',
      ctaText: 'Join Cohort · $749',
      ctaHref: '/un1/filmmaker/start?tier=film-cohort',
    },
    {
      id: 'film-accelerator',
      code: 'MYTHRA_ACCELERATOR',
      name: 'MYTHRA STUDIO ACCELERATOR',
      persona: 'FILMMAKER',
      price: 2500,
      priceDisplay: 'From $2,500',
      isStartingPrice: true,
      tagline: 'For working creators, agencies & small teams',
      description: 'Application-only 8–12 week program to build a repeatable production pipeline, team workflow, and commercial client offer.',
      features: [
        '8–12 week private agency/creator mentorship',
        'Build a repeatable multi-person production pipeline',
        'Quality control, client delivery & rights governance SOPs',
        'Portfolio polishing & commercial pitch decks',
        'Distribution strategy & audience testing frameworks',
        'Purely tactical execution and client acquisition architecture',
      ],
      deliverables: ['Private Studio Pipeline Setup', 'Commercial Asset Library', 'Client Contract & Delivery Templates'],
      turnaround: '8–12 Weeks',
      checkoutType: 'application',
      ctaText: 'Apply for Accelerator',
      ctaHref: '/un1/filmmaker/start?tier=film-accelerator',
    },
  ],

  // ── MYTHRA STUDIOS: Strategic Decision & Narrative Production ──
  studios: [
    {
      id: 'studio-opportunity-sprint',
      code: 'STUDIO_SPRINT',
      name: 'STORY OPPORTUNITY SPRINT',
      persona: 'STUDIOS',
      price: 2500,
      priceDisplay: '$2,500',
      tagline: 'FIND THE STORY · Strategic discovery before production',
      description: 'Before producing anything, discover which story your audience may actually care about. A strategic decision product, not a production package.',
      features: [
        'Brand, audience and cultural opportunity analysis',
        'Three original story territories engineered for your market',
        'Three core premises and dramatic opening hooks',
        'Recommended format and distribution model',
        'One selected concept developed into a complete treatment',
        'Initial character and world direction',
        'Pilot budget, timeline, and success criteria',
        'Executive presentation with creative leadership',
        '100% credited toward an approved $15K+ production within 30 days',
      ],
      deliverables: ['Story Opportunity Deck', 'Narrative Treatment', 'Pilot Budget & Decision Roadmap'],
      turnaround: '5–7 business days',
      checkoutType: 'deposit',
      ctaText: 'DISCOVER OUR STORY OPPORTUNITY',
      ctaHref: '/un1/studios/start?tier=story-sprint',
    },
    {
      id: 'studio-proof-pilot',
      code: 'STUDIO_PILOT',
      name: 'AUDIENCE PROOF PILOT',
      persona: 'STUDIOS',
      price: 7500,
      priceDisplay: 'From $7,500',
      standardPriceDisplay: '$10,000–$20,000 standard',
      isStartingPrice: true,
      isRecommended: true,
      tagline: 'PROVE THE STORY · Test whether the story deserves larger investment',
      description: 'You are not purchasing 45–90 seconds. You are purchasing evidence. We promise a professionally managed test and a clear decision to scale, revise, or stop.',
      features: [
        'One selected original concept developed to full screenplay',
        'Creative direction & narrative proof-of-concept production',
        'Multiple opening-hook variations for retention testing',
        'Horizontal (16:9) and vertical (9:16) launch versions',
        'Audience testing plan & hook validation framework',
        'Launch support on agreed digital channels',
        'Performance review & audience response mapping',
        'Clear scale, revise, or stop recommendation',
        'Expansion roadmap if audience signal is positive',
      ],
      deliverables: ['16:9 Master Pilot', '9:16 Social Cutdowns', 'Multi-Hook Testing Suite', 'Audience Signal Decision Report'],
      turnaround: '2–3 weeks',
      checkoutType: 'consultation',
      ctaText: 'TEST A STORY WITH MYTHRA',
      ctaHref: '/un1/studios/start?tier=proof-pilot',
    },
    {
      id: 'studio-story-world',
      code: 'STUDIO_WORLD',
      name: 'ORIGINAL ENTERTAINMENT PARTNERSHIP',
      persona: 'STUDIOS',
      price: 0,
      priceDisplay: 'Custom Scoped',
      tagline: 'OWN THE STORY WORLD · Scalable entertainment properties',
      description: 'Turn a validated concept into an enduring story world your company can build on. Series and original-IP partnerships are custom-scoped after the story has been validated.',
      features: [
        'Original branded entertainment property design',
        'Series and season dramatic architecture',
        'Comprehensive character and world bible',
        'Pilot and recurring episode production pipeline',
        'Reusable character, voice, and environment digital asset systems',
        'Territory localization strategy & multilingual launch',
        'Social cutdowns and syndication launch system',
        'Commercial rights and derivative property framework',
        'Audience performance reporting & future episode roadmap',
      ],
      deliverables: ['Season Master Episodes', 'Master World Bible', 'Reusable Asset System', 'Commercial Rights Package'],
      turnaround: 'Custom milestone timeline',
      checkoutType: 'consultation',
      ctaText: 'BUILD AN ORIGINAL STORY WORLD',
      ctaHref: '/un1/studios/start?tier=story-world',
    },
    {
      id: 'studio-licensing',
      code: 'STUDIO_LICENSE',
      name: 'LICENSE & LOCALIZE MYTHRA ORIGINALS',
      persona: 'STUDIOS',
      price: 0,
      priceDisplay: 'Territory Partnership',
      tagline: 'STRATEGIC PARTNERSHIP · For media companies & audience owners',
      description: 'License existing MYTHRA stories (such as Mother\'s Monster) for your language, channel, or territory. Minimum guarantee, fixed territory license, or revenue-share models.',
      features: [
        'License verified original MYTHRA stories with established audience traction',
        'Available for localized YouTube channels, streaming platforms, or broadcast',
        'Minimum guarantee, fixed territory license, or revenue-share structures',
        'Localization partnership with multi-language dubs and localized marketing',
        'Exclusive or non-exclusive territory rights available upon review',
      ],
      deliverables: ['Master Broadcast Files', 'Localization Dub Kit', 'Territory Distribution License'],
      turnaround: 'Executive agreement',
      checkoutType: 'consultation',
      ctaText: 'EXPLORE STORY LICENSING',
      ctaHref: '/un1/studios/start?intent=licensing',
    },
    {
      id: 'studio-coproduction',
      code: 'STUDIO_COPROD',
      name: 'FINANCE OR CO-PRODUCE MYTHRA ORIGINALS',
      persona: 'STUDIOS',
      price: 0,
      priceDisplay: 'Private Slate Review',
      tagline: 'STRATEGIC PARTNERSHIP · For investors & co-producers',
      description: 'Review selected MYTHRA story worlds, upcoming production slates, and global distribution opportunities. Requires application and executive qualification.',
      features: [
        'Application and qualification for private slate access',
        'Executive presentation of upcoming narrative slates & story worlds',
        'Detailed project economics, audience testing data, and financial modeling',
        'Milestone-governed co-production and IP rights participation frameworks',
        'Transparent risk disclosure, governance, and distribution architecture',
        'Direct confidential conversation with MYTHRA executive team',
      ],
      deliverables: ['Confidential Slate Presentation', 'Project Economics Model', 'Co-Production Term Sheet'],
      turnaround: 'Executive review',
      checkoutType: 'consultation',
      ctaText: 'REQUEST A PRIVATE SLATE CONVERSATION',
      ctaHref: '/un1/studios/start?intent=slate',
    },
  ],
};
