'use client';
import {useState,useRef,useEffect,type FormEvent} from 'react';
import {Check,Clapperboard,Globe2,Layers,Lightbulb,Orbit,Handshake,Mail,LockKeyhole} from 'lucide-react';
import {Checkbox} from '@/components/ui/checkbox';
import {RadioGroup,RadioGroupItem} from '@/components/ui/radio-group';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {Progress} from '@/components/ui/progress';
import {useStudio} from './content-provider';
const icons=[Clapperboard,Globe2,Layers,Lightbulb,Orbit,Handshake];
const budgets=['Exploring possibilities','Under $10,000','$10,000–$50,000','$50,000–$150,000','$150,000+','Prefer to discuss'];
const timelines=['Just exploring','Within 30 days','1–3 months','3–6 months','Long-term partnership'];
export function InquiryForm({kind='partner',initialCategory='Studios & producers',onStepChange}:{kind?:string,initialCategory?:string,onStepChange?:(step:number)=>void}){
 const data=useStudio();const simple=kind==='audience';const creator=kind==='creator';const[step,setStep]=useState(0);const[category,setCategory]=useState(initialCategory);const[consent,setConsent]=useState(false);const[marketing,setMarketing]=useState(false);const[status,setStatus]=useState('');const[error,setError]=useState('');const[requestId]=useState(()=>crypto.randomUUID());const[reference,setReference]=useState('');const formRef=useRef<HTMLFormElement>(null);const headingRef=useRef<HTMLHeadingElement>(null);const[first,setFirst]=useState(true);
 const[fields,setFields]=useState({name:'',email:'',company:'',role:'',country:'',phone:'',portfolio:'',message:'',budget:budgets[0],timeline:timelines[0],website:''});
 const update=(name:string,value:string)=>setFields(p=>({...p,[name]:value}));
 useEffect(()=>{onStepChange?.(step);if(!first)headingRef.current?.focus();setFirst(false)},[step]);
 function next(){if(!formRef.current?.reportValidity())return;setError('');setStep(Math.min(2,step+1))}
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!simple&&step<2){next();return}if(!consent){setError('Please confirm we may contact you about your request.');return}setStatus('saving');setError('');const url=new URL(location.href);const utm=Object.fromEntries(['utm_source','utm_medium','utm_campaign','utm_content','utm_term'].map(k=>[k,(url.searchParams.get(k)||'').slice(0,200)]));try{const r=await fetch('/api/inquiries',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...fields,category,kind,consent,marketingConsent:marketing,requestId,utm,pagePath:location.pathname,referrer:document.referrer?new URL(document.referrer).origin:''})});const body=await r.json() as {error?:string,reference?:string};if(!r.ok)throw new Error(body.error||'Your request could not be saved. Please try again.');setReference(body.reference||requestId.slice(0,8).toUpperCase());setStatus('saved')}catch(e){setStatus('');setError(e instanceof Error?e.message:'Please try again.')}}
 const input=(key:keyof typeof fields,label:string,placeholder:string,required=false,type='text',wide=false)=><label className={`field ${wide?'full':''}`} key={key}><span>{label}{!required&&<small>Optional</small>}</span><input name={key} type={type} value={fields[key]} onChange={e=>update(key,e.target.value)} required={required} maxLength={key==='email'?254:160} placeholder={placeholder} autoComplete={key==='name'?'name':key==='email'?'email':key==='phone'?'tel':key==='country'?'country-name':key==='company'?'organization':undefined} pattern={key==='phone'?'\\+[1-9][0-9\\s()-]{6,20}':undefined} title={key==='phone'?'Include country code, for example +44 7700 900000':undefined}/></label>;
 if(status==='saved')return <div className="inquiry-success" role="status" aria-live="polite"><div className="success-seal"><Check size={30}/></div><span className="eyebrow gold">THE NEXT CHAPTER</span><h3>{simple?"You're close to the story.":'A conversation\nworth beginning.'}</h3><p>{simple?'You are on the list for the MYTHRA experience.':`Thank you${fields.name?', '+fields.name.split(' ')[0]:''}. Your ${kind==='deck'?'partner deck request':'introduction'} is with the studio.`}</p><div className="receipt"><span>YOUR REFERENCE</span><strong>MYT—{reference}</strong><p>{simple?'Audience experience':category}</p></div>{kind==='deck'&&<p className="receipt-note">The studio will review your request. Deck delivery is handled personally.</p>}<a href="/world-001" className="textlink">Explore the world that started it</a></div>;
 if(simple)return <form ref={formRef} className="inquiry-form audience-form" onSubmit={submit}>{input('email','Your email','you@example.com',true,'email',true)}<div className="consent"><Checkbox id="audience-consent" checked={consent} onCheckedChange={v=>setConsent(v===true)}/><label htmlFor="audience-consent">Keep me updated about the MYTHRA experience. <a href="/privacy" className="underline">Privacy notice</a>.</label></div><label className="honey" aria-hidden="true">Leave blank<input value={fields.website} onChange={e=>update('website',e.target.value)} tabIndex={-1} autoComplete="off"/></label>{error&&<p role="alert" className="form-error">{error}</p>}<button className="btn btn-light" disabled={status==='saving'}>{status==='saving'?'Saving your place…':'Keep me close'}</button></form>;
 const choices=creator?[{name:'My story',description:'An idea, a script or a world waiting to be made.'},{name:'My audience',description:'A community ready for something extraordinary.'},{name:'My skills',description:'Craft, technology or talent that moves a story forward.'}]:kind==='press'?[{name:'Press & media',description:'Interviews, editorial coverage and press enquiries.'}]:data.partners;
 return <form ref={formRef} className="inquiry-form cinematic-form" onSubmit={submit}>
 <div className="journey-top"><span className="eyebrow">{kind==='deck'?'PARTNER DECK':creator?'CREATOR INTRODUCTION':'A NEW CONVERSATION'}</span><span>0{step+1} <span className="muted">/ 03</span></span></div><Progress value={(step+1)*100/3} aria-label={`Step ${step+1} of 3`} className="journey-progress"/><div className="step-labels"><span className={step===0?'current':''}>Your direction</span><span className={step===1?'current':''}>Your vision</span><span className={step===2?'current':''}>Your introduction</span></div>
 <div className="form-scene" key={step}><span className="eyebrow gold">CHAPTER 0{step+1}</span><h3 ref={headingRef} tabIndex={-1}>{step===0?(creator?'What will you bring?':'Where do our worlds meet?'):step===1?'Tell us what you see.':"Let's make the introduction."}</h3><p className="scene-intro">{step===0?'Choose the path that feels closest. We can discover the rest together.':step===1?'A few details help us bring the right people into the conversation.':'A real conversation starts with a name. Where can our studio reach you?'}</p>
 {step===0&&<RadioGroup aria-label="Partnership direction" value={category} onValueChange={setCategory} className="pathway-choices">{choices.map((c,i)=>{const Icon=icons[i%icons.length];return <label className={`pathway-choice ${category===c.name?'selected':''}`} key={c.name}><Icon className="pathway-icon" size={23} strokeWidth={1}/><span><strong>{c.name}</strong><small>{c.description}</small></span><RadioGroupItem value={c.name} aria-label={c.name}/></label>})}</RadioGroup>}
 {step===1&&<div className="fields vision-fields"><label className="field full"><span>{creator?'Your story, craft or idea':'What would you like to build with MYTHRA?'}<small>Optional</small></span><textarea name="message" value={fields.message} onChange={e=>update('message',e.target.value)} maxLength={4000} placeholder={creator?'The idea you cannot stop thinking about. The craft you want to bring.':'A story to develop, a territory to explore, a collaboration you can picture…'}/><span className="character-count">{fields.message.length} / 4,000</span></label>{kind!=='press'&&<><label className="field"><span>{creator?'Project resources':'Indicative budget'}</span><Select value={fields.budget} onValueChange={v=>update('budget',v)}><SelectTrigger aria-label="Indicative budget"><SelectValue/></SelectTrigger><SelectContent>{budgets.map(b=><SelectItem key={b} value={b}>{b}</SelectItem>)}</SelectContent></Select></label><label className="field"><span>When are you thinking?</span><Select value={fields.timeline} onValueChange={v=>update('timeline',v)}><SelectTrigger aria-label="Timeline"><SelectValue/></SelectTrigger><SelectContent>{timelines.map(b=><SelectItem key={b} value={b}>{b}</SelectItem>)}</SelectContent></Select></label></>}{input('portfolio',creator?'Portfolio or channel':'Website or reference','https://',false,'url',true)}<div className="confidential-note"><LockKeyhole size={15}/><span>Please share only a high-level introduction. Keep confidential scripts and materials for a later conversation.</span></div></div>}
 {step===2&&<><div className="selected-path"><span className="eyebrow">YOUR DIRECTION</span><strong>{category}</strong><button type="button" onClick={()=>setStep(0)}>Change</button></div><div className="fields">{input('name','Full name','Your name',true)}{input('email',creator?'Email':'Work email','you@company.com',true,'email')}{input('company',creator?'Creative focus':'Company or organization',creator?'Writer, filmmaker, animator…':'Your company',!creator)}{!creator&&input('role','Your role','Producer, founder, director…',true)}{input('country','Country','Where are you based?',true)}{input('phone','Phone / WhatsApp','+44 7700 900000',false,'tel')}</div><div className="consent"><Checkbox id={`consent-${kind}`} checked={consent} onCheckedChange={v=>setConsent(v===true)}/><label htmlFor={`consent-${kind}`}>MYTHRA may contact me about this enquiry using the details provided. <a href="/privacy" className="underline">Privacy notice</a>.</label></div><div className="consent marketing-consent"><Checkbox id={`marketing-${kind}`} checked={marketing} onCheckedChange={v=>setMarketing(v===true)}/><label htmlFor={`marketing-${kind}`}>I'd also like occasional MYTHRA news and new releases. Optional.</label></div></>}
 </div><label className="honey" aria-hidden="true">Leave blank<input value={fields.website} onChange={e=>update('website',e.target.value)} tabIndex={-1} autoComplete="off"/></label>{error&&<p className="form-error" role="alert">{error}</p>}<div className="journey-footer">{step>0?<button type="button" className="form-back" onClick={()=>{setError('');setStep(step-1)}} disabled={status==='saving'}>Back</button>:<span className="privacy-note"><LockKeyhole size={13}/> A direct line to the studio</span>}<button type="submit" className="btn btn-light" disabled={status==='saving'}>{status==='saving'?'Sending your introduction…':step<2?'Continue':kind==='deck'?'Request partner deck':creator?'Send my introduction':'Start the conversation'}</button></div></form>
}
export function InquiryBackdrop(){const data=useStudio();return <aside className="inquiry-backdrop"><img src={data.film.image} alt=""/><div className="inquiry-backdrop-top"><span className="brand">MYTHRA<small>STUDIOS</small></span><span className="eyebrow">PRIVATE INTRODUCTIONS</span></div><div className="inquiry-backdrop-copy"><span className="eyebrow gold">THE NEXT CHAPTER IS OPEN</span><h2>Great worlds<br/>begin with<br/><em>a conversation.</em></h2><p>Your ambition.<br/>Our imagination.<br/>Something worth making.</p><div className="backdrop-credit"><span>WORLD 001</span><strong>The Mother's Monster</strong><small>A world by {data.creator}</small></div></div></aside>}
