"use client";
import {useState,useEffect,useRef,createContext,useContext,type FormEvent} from 'react';
import {Play,Menu,X,Check,Plus} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {Checkbox} from '@/components/ui/checkbox';
import {useStudio} from './content-provider';
import {gsap} from 'gsap';
import {InquiryForm,InquiryBackdrop} from './inquiry-form';
export {InquiryForm} from './inquiry-form';
import {ScrollTrigger} from 'gsap/ScrollTrigger';

type ModalKind='partner'|'deck'|'proof'|'press'|null;
const ModalContext=createContext<(kind:ModalKind,category?:string)=>void>(()=>{});
export function PartnerButton({children,category,deck=false,className='btn',press=false}:{children:React.ReactNode,category?:string,deck?:boolean,className?:string,press?:boolean}){const open=useContext(ModalContext);return <button className={className} onClick={()=>open(press?'press':deck?'deck':'partner',category)}>{children}</button>}
export function WatchButton({children='Watch the film',className='btn btn-light'}:{children?:React.ReactNode,className?:string}){const data=useStudio();return <a href={data.film.url} target="_blank" rel="noreferrer" className={className}><Play size={13} fill="currentColor"/>{children}</a>}
export function Header(){const[menu,setMenu]=useState(false);return <header className="nav"><a href="/" className="brand" aria-label="MYTHRA Studios home">MYTHRA<small>STUDIOS</small></a><nav className="navlinks" aria-label="Main"><a href="/#world">World 001</a><a href="/#studio">The studio</a><a href="/#partners">Partnerships</a><a href="/enter">Enter Mythra</a><PartnerButton className="nav-cta">Let's talk</PartnerButton></nav><button className="menu-btn" aria-label={menu?'Close navigation':'Open navigation'} aria-expanded={menu} onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button>{menu&&<nav className="mobile-panel" aria-label="Mobile"><a onClick={()=>setMenu(false)} href="/#world">World 001</a><a onClick={()=>setMenu(false)} href="/#studio">The studio</a><a onClick={()=>setMenu(false)} href="/#partners">Partnerships</a><a href="/join">Creators</a><a href="/enter">Enter Mythra</a></nav>}</header>}
export function Shell({children}:{children:React.ReactNode}){const data=useStudio();const[kind,setKind]=useState<ModalKind>(null);const[category,setCategory]=useState('Studios & producers');const[reduced,setReduced]=useState(false);useEffect(()=>{const value=localStorage.getItem('mythra-motion');const r=value?value==='reduced':matchMedia('(prefers-reduced-motion: reduce)').matches;setReduced(r);document.documentElement.classList.toggle('reduced-motion',r)},[]);function toggleMotion(){const value=!reduced;setReduced(value);localStorage.setItem('mythra-motion',value?'reduced':'full');document.documentElement.classList.toggle('reduced-motion',value)}return <ModalContext.Provider value={(k,c)=>{setCategory(c||'Studios & producers');setKind(k)}}><a href="#main" className="skip-link">Skip to content</a>{children}<Footer reduced={reduced} toggleMotion={toggleMotion}/><Dialog open={!!kind} onOpenChange={v=>{if(!v)setKind(null)}}><DialogContent className={kind==='proof'?'modal':'modal cinematic-modal'}>{kind==='proof'?<><DialogTitle>A story that travelled.</DialogTitle><DialogDescription>{data.metricNote}</DialogDescription><div style={{display:'grid',gap:15,marginTop:15}}>{data.metrics.map(m=><p key={m.platform}><strong>{m.value}</strong> {m.platform} · {m.detail.toLowerCase()}</p>)}<p><strong>{data.worldwide}</strong> worldwide views, reported by MYTHRA.</p><p>Figures supplied by the studio, September 2026. Independent verification is not represented.</p></div></>:<><DialogTitle className="sr-only">Begin a conversation with MYTHRA</DialogTitle><DialogDescription className="sr-only">Three steps: choose your direction, share your vision, and introduce yourself.</DialogDescription><InquiryBackdrop/><div className="inquiry-panel"><InquiryForm key={`${kind}-${category}`} kind={kind||'partner'} initialCategory={kind==='press'?'Press & media':category}/></div></>}</DialogContent></Dialog></ModalContext.Provider>}
export function Footer({reduced,toggleMotion}:{reduced:boolean,toggleMotion:()=>void}){const data=useStudio();return <footer className="footer"><div className="footer-top"><div><a href="/" className="brand">MYTHRA<small>STUDIOS</small></a><p>An AI-native story and IP studio.</p>{data.partnersEmail&&<p>Partnerships: <a href={`mailto:${data.partnersEmail}`}>{data.partnersEmail}</a></p>}{data.pressEmail&&<p>Press: <a href={`mailto:${data.pressEmail}`}>{data.pressEmail}</a></p>}{data.socials.length>0&&<div className="footer-nav" style={{marginTop:20}}>{data.socials.map(s=><a key={s.name} href={s.url} target="_blank" rel="noreferrer">{s.name}</a>)}</div>}</div><nav className="footer-nav" aria-label="Footer"><a href="/#world">World 001</a><a href="/#studio">Studio</a><a href="/#partners">Partners</a><a href="/join">Creators</a><PartnerButton press className="footer-text">Press</PartnerButton><PartnerButton className="footer-text">Contact</PartnerButton></nav></div><div className="footer-bottom"><span>© 2026 MYTHRA Studios{data.legalEntity&&` · ${data.legalEntity}`}</span><div className="legal-links"><a href="/privacy">Privacy & cookies</a><a href="/terms">Terms</a><button onClick={toggleMotion}>Motion: {reduced?'Reduced':'Full'}</button></div><span>HUMAN-LED. AI-NATIVE.</span></div></footer>}
export function Home(){const data=useStudio();const open=useContext(ModalContext);const frame=useRef<HTMLImageElement>(null);const steps=useRef<HTMLDivElement>(null);const[active,setActive]=useState(0);useEffect(()=>{gsap.registerPlugin(ScrollTrigger);const media=gsap.matchMedia();media.add('(prefers-reduced-motion: no-preference)',()=>{const tween=frame.current?gsap.fromTo(frame.current,{scale:1.1},{scale:1,ease:'none',scrollTrigger:{trigger:frame.current.parentElement,start:'top bottom',end:'bottom top',scrub:true}}):null;const trigger=steps.current?ScrollTrigger.create({trigger:steps.current.parentElement,start:'top center',end:'bottom center',onUpdate:self=>setActive(Math.min(3,Math.floor(self.progress*4)))}):null;return()=>{tween?.kill();trigger?.kill()}});return()=>media.revert()},[]);return <><Header/><main id="main"><section className="hero"><img className="hero-media" src={data.film.image} alt="A mother beside the dragon from The Mother's Monster" fetchPriority="high"/><div className="hero-topline"><span className="eyebrow gold">Independent imagination. Worldwide resonance.</span><span className="eyebrow right">HUMAN-LED · AI-NATIVE</span></div><h1>WE MAKE STORIES<br/>PEOPLE <em>CARRY FORWARD.</em></h1><p className="hero-copy">An AI-native story and IP studio creating original entertainment for a global audience.</p><div className="actions"><WatchButton>Watch The Mother's Monster</WatchButton><PartnerButton>Partner with MYTHRA</PartnerButton></div><div><PartnerButton deck className="textlink decklink">Request partner deck</PartnerButton></div><div className="hero-proof"><div className="global-stat"><strong>{data.worldwide}</strong><span>Reported worldwide views</span></div>{data.metrics.map(m=><div className="metric" key={m.platform}><strong>{m.value}</strong><span>{m.platform}</span><small>{m.detail}</small></div>)}</div>{data.festival&&<p className="eyebrow gold" style={{fontSize:11,marginBottom:10}}>{data.festival}</p>}<div className="proof-foot"><span>ONE STORY. CARRIED ACROSS THE WORLD. · <button onClick={()=>open('proof')}>About these numbers</button></span><span>SCROLL TO DISCOVER &nbsp; 01 / 06</span></div></section>
<section className="section" id="world"><div className="section-label eyebrow"><span className="gold">01 — THE FIRST WORLD</span><span>ORIGINAL IP · MYTHRA STUDIOS</span></div><div className="world-intro"><h2>THE MOTHER'S<br/><em>MONSTER.</em></h2><p>A mother. A creature the world feared.<br/>And a bond stronger than fear.</p></div><div className="film-frame"><img ref={frame} src={data.film.image} alt="The mother and her dragon in a snow-covered landscape" loading="lazy"/><div className="film-caption"><div><p className="eyebrow gold">WORLD 001 · NOW SHOWING</p><h3>Love was never<br/>the monster.</h3></div><a href={data.film.url} target="_blank" rel="noreferrer" className="play-circle" aria-label="Watch The Mother's Monster"><Play size={20} fill="currentColor"/></a></div></div><div className="world-bottom"><p>It began as an AI-native film. Then the audience took it further. Watched. Shared. Translated. Remixed. Carried across platforms, languages and communities.</p><div><h3 className="serif" style={{fontSize:34,lineHeight:1.15}}>That's when a story<br/>starts becoming a world.</h3><a href="/world-001" className="textlink" style={{marginTop:22}}>Explore World 001</a></div></div><div className="creator"><span className="eyebrow muted">A world begins<br/>with a storyteller.</span><div className="creator-name"><span className="eyebrow gold" style={{display:'block',marginBottom:10}}>CREATED BY</span>{data.creator}<small>Creator of World 001: The Mother's Monster</small></div></div></section>
<section className="method"><div className="method-copy"><span className="eyebrow gold">02 — THE METHOD</span><h2>Make a story.<br/>Listen to<br/><em>the world.</em></h2><p>We create original stories and put them in front of real audiences. Then we watch what travels. The moments shared. The characters remembered. The worlds people return to.</p><p>Story first. Audience signal second.<br/>Expansion after that.</p></div><div className="method-steps" ref={steps}>{['BUILD.','RELEASE.','LISTEN.','EXPAND.'].map((s,i)=><div key={s} className={`method-step ${active===i?'active':''}`}><small>0{i+1}</small><span>{s}</span></div>)}</div></section>
<section className="studio" id="studio"><div><span className="eyebrow gold">03 — THE STUDIO</span><h2>STORY IS WHERE<br/>WE START.<br/><em>IP IS WHAT<br/>WE'RE BUILDING.</em></h2><span className="eyebrow muted">HUMAN-LED · AI-NATIVE</span></div><div className="studio-right"><p>Film can be where a world begins. It doesn't have to be where it ends. The right MYTHRA worlds can grow through:</p><div className="possibilities"><span>Distribution.</span><span>Localization.</span><span>New stories.</span><span>Publishing.</span><span>Interactive experiences.</span><span>Consumer products.</span><span>Licensing.</span></div><div className="trust"><span className="eyebrow gold">BUILT FOR PARTNERSHIP</span><p>{data.rightsStatement||`Original world created by ${data.creator}. Rights scope and production documentation are discussed for each partnership.`}</p><p>AI changes how quickly a small creative team can build, localize and release ambitious entertainment. Technology isn't the product. The story is.</p></div></div></section>
<section className="partners" id="partners"><div className="section-label eyebrow"><span>04 — PARTNERSHIPS</span><span>THE NEXT CHAPTER IS OPEN</span></div><div className="partners-head"><h2>THERE ARE MANY<br/>WAYS <em>INTO</em><br/>A MYTHRA WORLD.</h2><p>For the people who see what a story could become. Let's find the right way to build together.</p></div><div className="partner-grid">{data.partners.map((p,i)=><button className="partner-row" key={p.name} onClick={()=>open('partner',p.name)}><small>0{i+1}</small><div><h3>{p.name}</h3><p>{p.description}</p></div><Plus size={18}/></button>)}</div><div className="actions"><PartnerButton className="btn btn-dark">Partner with MYTHRA</PartnerButton><PartnerButton deck className="textlink">Request partner deck</PartnerButton></div></section>
<section className="doors"><div className="door"><span className="eyebrow gold">05 — FOR CREATORS</span><h2>The next great studio<br/>may look nothing<br/>like the last one.</h2><p>Bring your story, your audience or your skills.</p><a href="/join" className="textlink">Join the creator network</a></div><div className="door"><img src="/images/egg.webp" alt="Concept art of a mysterious dragon egg in a dark temple" loading="lazy"/><span className="eyebrow gold">06 — FOR THE AUDIENCE</span><h2>You don't have<br/>to be a company<br/>to enter MYTHRA.</h2><p>Watch the stories. Follow the worlds.<br/>Find what others miss.</p><a href="/enter" className="textlink">Enter MYTHRA</a><span className="eyebrow" style={{fontSize:10,marginTop:17,color:'#a8ad9b'}}>FIND THE EGG.</span></div></section><section className="final"><span className="eyebrow gold">THIS IS ONLY THE BEGINNING</span><h2 style={{marginTop:35}}>STORIES BECOME WORLDS.<br/>WORLDS BECOME IP.<br/><em>AND SOMETIMES,<br/>THOSE WORLDS BECOME REAL.</em></h2><p>We make stories people carry forward.</p><div className="actions"><WatchButton>Watch World 001</WatchButton><PartnerButton>Partner with MYTHRA</PartnerButton></div></section></main></>}
