export type GhlConfig={apiKey:string;locationId:string;pipelineId:string;stageId:string;version?:string};
export type GhlLead={id:string;kind:string;name:string;email:string;company:string;role:string;country:string;category:string;message:string;phone:string;portfolio:string;budget:string;timeline:string;marketingConsent:number;attribution:string;createdAt:string};
export type GhlCheckpoint={contactId:string;opportunityId:string;noteId:string};
export class GhlError extends Error{constructor(message:string,public reviewRequired=false){super(message)}}
const BASE='https://services.leadconnectorhq.com';
export async function deliverGhlLead(config:GhlConfig,lead:GhlLead,checkpoint:GhlCheckpoint,save:(next:GhlCheckpoint)=>Promise<void>,fetcher:typeof fetch=fetch){
 const state={...checkpoint};
 async function call(path:string,method='GET',body?:unknown,ambiguousWrite=false):Promise<any>{let response:Response;try{response=await fetcher(BASE+path,{method,headers:{Authorization:`Bearer ${config.apiKey}`,Version:config.version||'2021-07-28',Accept:'application/json',...(body?{'Content-Type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{}),signal:AbortSignal.timeout(12000)})}catch{throw new GhlError('GHL connection did not complete. '+(ambiguousWrite?'Review the CRM before retrying this request.':'The lead is saved for retry.'),ambiguousWrite)}if(!response.ok){throw new GhlError(`GHL returned HTTP ${response.status}. ${response.status===401||response.status===403?'Check the private integration token and its location/scopes.':'The lead remains saved.'}`,ambiguousWrite&&response.status>=500)}try{return await response.json()}catch{throw new GhlError('GHL returned an unreadable response.',ambiguousWrite)}}
 const pipelines=await call(`/opportunities/pipelines?locationId=${encodeURIComponent(config.locationId)}`);const pipeline=pipelines.pipelines?.find((p:any)=>p.id===config.pipelineId);if(!pipeline?.stages?.some((s:any)=>s.id===config.stageId))throw new GhlError('The configured GHL pipeline or stage could not be verified for this location.');
 if(!state.contactId){const name=lead.name.trim().split(/\s+/);const payload={email:lead.email,locationId:config.locationId,...(lead.name?{firstName:name[0],lastName:name.slice(1).join(' ')}:{}),...(lead.phone?{phone:lead.phone}:{}),...(lead.company?{companyName:lead.company}:{}),...(lead.portfolio?{website:lead.portfolio}:{}),source:'MYTHRA cinematic studio',createNewIfDuplicateAllowed:false};const result=await call('/contacts/upsert','POST',payload);state.contactId=result.contact?.id||'';if(!state.contactId)throw new GhlError('GHL did not return a contact ID.');await save({...state})}
 const slug=lead.category.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');await call(`/contacts/${encodeURIComponent(state.contactId)}/tags`,'POST',{tags:['mythra','mythra-studio-site',`mythra-${lead.kind}`,`mythra-interest-${slug}`,...(lead.marketingConsent?['mythra-news-opt-in']:[])]});
 if(!state.opportunityId){const qs=new URLSearchParams({location_id:config.locationId,pipeline_id:config.pipelineId,contact_id:state.contactId,status:'all',limit:'100'});const existing=await call(`/opportunities/search?${qs}`);const match=existing.opportunities?.find((o:any)=>o.contactId===state.contactId||o.contact?.id===state.contactId);if(match){state.opportunityId=match.id}else{const result=await call('/opportunities/','POST',{pipelineId:config.pipelineId,locationId:config.locationId,name:`MYTHRA · ${lead.category} · ${lead.name||lead.email}`,pipelineStageId:config.stageId,status:'open',contactId:state.contactId},true);state.opportunityId=result.opportunity?.id||'';if(!state.opportunityId)throw new GhlError('Opportunity response was incomplete. Review GHL before retrying.',true)}await save({...state})}
 if(!state.noteId){const marker=`MYTHRA request ${lead.id}`;const existing=await call(`/contacts/${encodeURIComponent(state.contactId)}/notes`);const found=existing.notes?.find((n:any)=>typeof n.body==='string'&&n.body.includes(marker));if(found){state.noteId=found.id}else{const body=[marker,`Received: ${lead.createdAt}`,`Type: ${lead.kind}`,`Interest: ${lead.category}`,`Company: ${lead.company||'—'}`,`Role: ${lead.role||'—'}`,`Country: ${lead.country||'—'}`,`Phone: ${lead.phone||'—'}`,`Portfolio/reference: ${lead.portfolio||'—'}`,`Budget: ${lead.budget||'—'}`,`Timeline: ${lead.timeline||'—'}`,`Contact permission: Yes (submitted with request)`,`Marketing permission: ${lead.marketingConsent?'Yes':'No'}`,`Attribution: ${lead.attribution||'{}'}`,'',lead.message||'No additional brief.'].join('\n');const result=await call(`/contacts/${encodeURIComponent(state.contactId)}/notes`,'POST',{body},true);state.noteId=result.note?.id||'';if(!state.noteId)throw new GhlError('Note response was incomplete. Review GHL before retrying.',true)}await save({...state})}return state;
}
